In [7]:
import numpy as np
arr = np.array([1,2,3,4,5],dtype=float)
print(arr)
reshaped_arr =arr.reshape(5,1)
print(reshaped_arr)
sliced_arr = arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8,])
b=a.T
print(b)
b=np.split(a,4)
print(b)
a = np.array([[1,2],[3,4]])
b =np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d= np.linalg.eig(c)
print(d)
arange_arr=np.arange(0,100,5)
print(arange_arr)
d = np.savetxt("/content/date.txt",arange_arr)
a=np.random.rand()
print(a)
g=np.random.randint(2,10)
print(g)
a=np.array([[1,2],[3,4]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
a=np.linspace(0.8,2,5)
print(a)
a=np.arange(0,6)
print(a)
n=np.arange(24).reshape(3,4,2)
print(n)
a = np.array([[1,2],[3,4]])
b =np.array([[5,6],[7,8]])
print(a*b)
print(a@b)
from numpy import random
a=np.ones((2,3))
print(a)
print(a.sum())
print(a.max())
print(a.max(axis=1))
print(a.max(axis=0))
a=np.ceil(np.random.random((2,12)))
print(a)
c=np.random.random((2,2))
print(c)
from numpy import random
a=np.ones((2,3))
print(a)
print(a.cumsum())
print(a.cumsum())
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))
a = np.array([[1,2],[3,4]])
print(a)
a=np.array([2,3,5,6])
print(a.cumsum())
a=np.array([2,3,5,6,7,8,9])
b=a.resize([2,3])
print(a)
print(b)
a=np.array([2,3,5,6,7,8])
a.resize([2,3])
a=np.array([6,1,7,6,7,9])
a1=np.eye(4)
print(a1)

[1. 2. 3. 4. 5.]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[3. 4.]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
0.3099165230366733
7
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
2
(2, 2)
[0.8 1.1 1.4 1.7 2. ]
[0 1 2 3 4 5]
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[1. 1. 1.]
 [1. 1. 1.]]
6.0
1.0
[1. 1.]
[1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.96760319 0.22854493]
 [0.56771549 0.51250733]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]
[[1. 2. 3.]
 [1. 2. 3.]]
[[1. 1. 1.]
 [2. 2. 2.]]
[[1 2]
 [3 4]]
[ 2  5 10 16]
[[2 3 5]
 [6 7 8]]
None
[[1. 0. 0. 0.]
 [

In [ ]:
import numpy as np
data = np.loadtxt("/content/drive/MyDrive/dataset/data.txt",dtype=int)
d = np.savetxt("/content/drive/MyDrive/dataset/date.txt",data)
print(d)
print(data)
arange_arr=np.arange(0,100,5)
print(arange_arr)



np.cross output is incorrect order
so we take martix in vertical

In [10]:
a1= np.full((2,2),3)
print(a1)
print(a1.itemsize)
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))


[[3 3]
 [3 3]]
8
[1 2 3]
<class 'numpy.ndarray'>
10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [47]:
a=np.array([6.3,1.5,7.7,6.1,7.9,9.4])
np.rint(a)
a=np.array([6,1,7,6,7])
b=np.array([2,3,2,6,7])
np.true_divide(a,b)
a=np.array([6,6,7,7,1,1])
np.unique(a)
a=np.array(([6,2],[2,2]))
b=np.array(([4,5],[6,7]))
np.union1d(a,b)
a=np.array(([6,2],[2,2]))
b=np.array(([4,5],[6,7]))
np.intersect1d(a,b)
a=np.array(([6,1],[2,2]))
b=np.array(([4,9],[6,7]))
np.setdiff1d(a,b)
a=8
b=6
c=np.hypot(a,b)
print(c)
x=np.sin(0)
print(x)
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.mod(a,b)
print(c)
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)
print(c)
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.multiply(a,b)
print(c)


10.0
0.0
(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))
[10  0  0  0  0 10]
[ 0.5  1.  15.   2.   2.   2.4]
[ 200  441   60  800 1250 1500]


loc=meanval scale=standard devation


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)
x=random.binomial(n=12,p=0.5,size=10)
print(x)
x=random.poisson(lam=2,size=10)
print(x)
x=random.choice([1,2,3,4,5])
print(x)
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

In [ ]:
v_arr = np.zeros((3,3), dtype=int)
print(v_arr)
s_arr = np.ones((2,2), dtype=int)
print(s_arr)
arange_arr=np.arange(10)
print(arange_arr)
reshaped_arr =arr.rshaped(5,1)
print(reshaped_arr)